[build]
target = "../../x86_64-ralph_program.json"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-arg=-T../../program.ld"]
