[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-ralph_os.json"

[target.x86_64-ralph_os]
rustflags = ["-C", "link-arg=-Tkernel.ld", "-C", "link-arg=--gc-sections"]
